### ISSUE TITLE
Patreon Discord link broken

### ISSUE THREAD

**Issue by d0nutptr** [PostGraphDB/postgraph#265]
**Describe the bug**
Patreon discord link is broken

**How are you accessing AGE (Command line, driver, etc.)?**
Discord

**What data setup do we need to do?**
Become a patreon supporter

**What is the necessary configuration info needed?**
Money

**What is the command that caused the error?**
"Join Server"

**Expected behavior**
I'm able to join the discord

**Environment (please complete the following information):**
Ubuntu 22.04

**Additional context**
N/A

**Comment by JoshInnis** [comment]
https://discord.gg/XEp56VaqZs

**Comment by JoshInnis** [comment]
The link in Discord should work and you should have your permissions now.
