### ISSUE TITLE
Detailed information about the project.

### ISSUE THREAD

**Issue by arun-esh** [PostGraphDB/postgraph#286]
**Is your feature request related to a problem? Please describe.**
The current README has the placeholder information for the project. But a detailed information about the project is missing.

**Describe the solution you'd like**

- Postgraph is an extension to Postgres but which version of Postgres is compatible with PostGraph. 
- How to install/ configure the Postgraph on multiple OS.

**Describe alternatives you've considered**
There is no alternative to a better README

**Additional context**

**Comment by JoshInnis** [comment]
Yeah we are going to need to rethink the entire documentation system. It needs to be expanded and rewritten. Maybe even have Youtube videos walking people through steps and features. There is a project that was created, but its not setup yet.

https://github.com/orgs/PostGraphDB/projects/12/views/1

**Comment by arun-esh** [comment]
> Yeah we are going to need to rethink the entire documentation system. It needs to be expanded and rewritten. Maybe even have Youtube videos walking people through steps and features. There is a project that was created, but its not setup yet.
> 
> https://github.com/orgs/PostGraphDB/projects/12/views/1

Walk-through videos + 1

**Comment by JoshInnis** [comment]
Part of the problem with AGE was how to use it well. Which was never explained very well.

**Comment by JoshInnis** [comment]
Yeah, I think embedding videos in sections of the documentation will be really helpful. Not just installation and setup, but using PostGraph too.

**Comment by JoshInnis** [comment]
Thats for a devlopers section. So there needs to be a manual for users and for people who want to develop PostGraph
