### ISSUE TITLE
Bug: No rule to make target 'src/backend/utils/adt/gtype_network.o', needed by 'postgraph.so'

### ISSUE THREAD

**Issue by MatheusFarias03** [PostGraphDB/postgraph#358]
### Describe the bug

When attempting to install PostGraph, I receive an error message: `No rule to make target 'src/backend/utils/adt/gtype_network.o', needed by 'postgraph.so'.` It appears that the file `gtype_network.c` does not exist under the `src/backend/utils/adt/` directory, which I believe is causing this issue.

### Steps to reproduce

1. Clone the PostGraph repository from GitHub.
2. Navigate to the repository directory.
3. Execute the 'make' command to build PostGraph: `sudo make PG_CONFIG=~/path/to/postgresql/bin/pg_config install`

### Expected behaviour

I expected the make command to successfully build PostGraph without any errors.

### PostGraph version

postgraph 0.1.0 - PG14 - Fedora 38

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JoshInnis** [comment]
This should be resolved. There was a missing file in github that has been added
